### ISSUE TITLE
Fix: Elastic Beanstalk 운영서버 구축 이슈 (Elastic Beanstalk + Git Action + Spring boot)

### ISSUE THREAD

**Issue by yeahdy** [LuckyVicky-2team/backend#91]
## 어떤 버그인가요?
- GitHub Action 을 통해 운영 서버에 배포 시 Elastic Beanstalk 302 이슈 발생

## 어떤 상황에서 발생한 버그인가요?
1. dev >prod 브랜치로 PR 시 깃헙 액션 CD 실행
2. Elastic Beanstalk deploy 테스크에서 에러 발생
[에러 내용]
**Error: Deployment failed: Error: Deployment failed! Current State: Version: null, Health: Grey, Health Status: null**
![image](https://github.com/user-attachments/assets/45098a8c-129d-42c2-a740-e2b92d6c9e85)

## 예상 결과
- Elastic Beanstalk 운영 서버 배포 및 spring boot 실행 성공
<img src="https://github.com/user-attachments/assets/ab239091-e4ce-40f4-a45d-c14b89a1d6f1" width="600" height="350"/>

### Elastic Beanstalk 로그파일 다운로드
- eb-engin.log 파일에는 명시된 에러 로그가 없었고, 배포를 통해 만들어진 배치 EC2에 application.jar 파일이 있는것을 확인함
- 배포는 되었지만, ec2 인스턴스가 unhealthy 상태였고 302 에러를 뱉고 있었음.

### Elastic Beanstalk nginx 로그 확인

> \var\log\nginx\access 확인<img src="https://github.com/user-attachments/assets/76f0270e-053b-45c5-9bff-242f6060f11d" width="700" height="200"/>

> \var\log\nginx\error 확인
![nginx_error](https://github.com/user-attachments/assets/46ed8d46-7f8d-4948-a954-3e3be8299ea4)

**결론은 상태 확인 요청에 대해 백엔드로부터 "200 OK" 응답을 받아야 하는데, 성공코드로 분류되어 있지 않은 302 코드를 반환하기 때문에 에러로 인식하는 것!** 

### `302`코드가 어떤걸 의미하는거지?
`302`는 리다이렉션을 의미하는 HTTP 상태 코드로 요청한 리소스가 일시적으로 다른 URL로 이동되었다는 것을 나타낸다.
**HTTP요청을 HTTPS 로 리다이렉트할 때 301 또는 302를 반환**하게 되는데, 우리 백엔드 서버는 HTTP > HTTPS 로 리다이렉트를 한다!
[AWS health checks](https://repost.aws/ko/knowledge-center/troubleshoot-classic-health-checks) 참고

### 해결
**EB 에서 발생한 302 에러는 HTTP요청을 HTTPS 로 리다이렉트할 때 반환하는 정상적인 상태 코드이기 때문에 EB 의 대상그룹에서 302 HTTP code를 성공코드로 등록 해 주면 된다**

**Comment by ambosing** [comment]
오 해결하신건가요 ?
마지막에 해결되어 있는데
